insert into movie (id, name, director_id, country_of_origin, release_year) values (1, 'Lightning Bug', 19, 'Brazil', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (2, 'Summer''s Tale, A (Conte d''été)', 4, 'Czech Republic', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (3, 'African Cats', 4, 'France', 1989);
insert into movie (id, name, director_id, country_of_origin, release_year) values (4, 'Under the Skin of the City (Zir-e-poost-e Shahr)', 17, 'Indonesia', 2003);
insert into movie (id, name, director_id, country_of_origin, release_year) values (5, 'Guest from the Future (Gostya iz buduschego)', 13, 'China', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (6, 'Repo! The Genetic Opera', 17, 'Brazil', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (7, 'City, The (Ciudad, La)', 19, 'Russia', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (8, 'Monkey''s Mask, The', 13, 'China', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (9, 'Dr. Akagi (Kanzo sensei)', 17, 'Portugal', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (10, 'Greenwich Village: Music That Defined a Generation ', 8, 'China', 1990);
insert into movie (id, name, director_id, country_of_origin, release_year) values (11, 'Once Upon a Forest', 18, 'Peru', 1965);
insert into movie (id, name, director_id, country_of_origin, release_year) values (12, 'White Angel, The (L''angelo bianco)', 11, 'China', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (13, 'White Angel, The (L''angelo bianco)', 17, 'Philippines', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (14, 'Joker', 7, 'Nicaragua', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (15, 'Wolves', 17, 'Cyprus', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (16, 'Seven Little Foys, The', 2, 'Russia', 1986);
insert into movie (id, name, director_id, country_of_origin, release_year) values (17, 'I Am a Sex Addict', 1, 'Brazil', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (18, 'Ice Age 4: Continental Drift', 3, 'Brazil', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (19, 'Santa Who?', 6, 'Portugal', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (20, 'Filth', 18, 'Russia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (21, 'Fûke, De', 5, 'Russia', 1987);
insert into movie (id, name, director_id, country_of_origin, release_year) values (22, 'Notorious', 20, 'China', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (23, 'Normal Adolescent Behavior', 8, 'El Salvador', 1987);
insert into movie (id, name, director_id, country_of_origin, release_year) values (24, 'Miss Sadie Thompson', 7, 'Peru', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (25, 'Chechahcos, The', 6, 'Poland', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (26, 'Moonfleet', 17, 'Indonesia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (27, 'For a Woman (Pour une femme)', 15, 'Croatia', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (28, 'Hole, The', 13, 'South Korea', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (29, 'Louis C.K.: Live at The Comedy Store', 11, 'United States', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (30, 'Mental', 12, 'China', 1963);
insert into movie (id, name, director_id, country_of_origin, release_year) values (31, 'Gabriela', 16, 'Brazil', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (32, 'Cold Light of Day, The', 12, 'China', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (33, 'Fright Night Part II', 12, 'Indonesia', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (34, 'Blondes at Work', 14, 'Sweden', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (35, 'Mr. Woodcock', 14, 'Russia', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (36, 'Hard Corps, The', 10, 'France', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (37, 'Breathless (Ddongpari)', 19, 'Yemen', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (38, 'Return of the Living Dead: Rave to the Grave', 13, 'Sudan', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (39, 'Neighbors', 18, 'China', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (40, 'Soldier of Fortune', 19, 'Greece', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (41, '9500 Liberty', 17, 'Guatemala', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (42, 'Wildflowers', 8, 'Portugal', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (43, 'Beauty and the Beast', 12, 'Honduras', 1986);
insert into movie (id, name, director_id, country_of_origin, release_year) values (44, 'Cat Chaser', 7, 'Nicaragua', 2003);
insert into movie (id, name, director_id, country_of_origin, release_year) values (45, 'Soldier of Orange (a.k.a. Survival Run) (Soldaat van Oranje)', 8, 'United States', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (46, 'Treasure of the Sierra Madre, The', 3, 'Indonesia', 1989);
insert into movie (id, name, director_id, country_of_origin, release_year) values (47, 'Five Senses, The', 4, 'Argentina', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (48, 'Men Don''t Leave', 14, 'France', 1984);
insert into movie (id, name, director_id, country_of_origin, release_year) values (49, 'Kids in the Hall: Brain Candy', 19, 'Brazil', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (50, 'My Life and Times With Antonin Artaud (En compagnie d''Antonin Artaud)', 7, 'Russia', 1985);
insert into movie (id, name, director_id, country_of_origin, release_year) values (51, 'The True Story of Puss ''n Boots', 16, 'Indonesia', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (52, 'Broadway Danny Rose', 17, 'China', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (53, 'Cardinal, The', 7, 'Mexico', 1987);
insert into movie (id, name, director_id, country_of_origin, release_year) values (54, 'Madness of King George, The', 2, 'Estonia', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (55, 'Getaway, The', 15, 'China', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (56, 'Mr. Death: The Rise and Fall of Fred A. Leuchter, Jr.', 10, 'Serbia', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (57, 'Village, The', 4, 'Kenya', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (58, 'Subway', 18, 'Tanzania', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (59, 'Let Fury Have the Hour', 12, 'Canada', 1984);
insert into movie (id, name, director_id, country_of_origin, release_year) values (60, 'That Night''s Wife', 6, 'United States', 1989);
insert into movie (id, name, director_id, country_of_origin, release_year) values (61, 'Peacock', 5, 'Czech Republic', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (62, 'Within Limits (Liikkumavara)', 12, 'Indonesia', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (63, 'Victor and the Secret of Crocodile Mansion', 4, 'Indonesia', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (64, 'Stealing Harvard', 16, 'United States', 1958);
insert into movie (id, name, director_id, country_of_origin, release_year) values (65, 'Hiroshima Mon Amour', 5, 'Netherlands', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (66, 'Wedding Date, The', 16, 'United States', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (67, 'Nacho Libre', 19, 'South Africa', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (68, 'Dog Year, A', 8, 'Albania', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (69, 'Choices', 18, 'Macedonia', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (70, 'Gigante', 5, 'China', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (71, 'Trap: What Happened to Our Dream of Freedom, The', 2, 'Kosovo', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (72, 'Show People', 7, 'China', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (73, '12 Angry Men', 13, 'Bangladesh', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (74, 'Living Desert, The', 6, 'Portugal', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (75, 'Shinjuku Incident (San suk si gin)', 1, 'Brazil', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (76, 'Terror''s Advocate (Avocat de la terreur, L'')', 1, 'Sweden', 1970);
insert into movie (id, name, director_id, country_of_origin, release_year) values (77, 'Return to Horror High', 20, 'Ethiopia', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (78, 'Gamera vs. Gyaos (Daikaijû kûchûsen: Gamera tai Gyaosu)', 14, 'China', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (79, 'Girl with Green Eyes', 7, 'Iran', 1955);
insert into movie (id, name, director_id, country_of_origin, release_year) values (80, 'Quicksilver', 2, 'Finland', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (81, 'Comet in Moominland', 15, 'Slovenia', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (82, 'Demetrius and the Gladiators', 18, 'Kazakhstan', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (83, 'Bataan', 1, 'Thailand', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (84, 'Sunset Park', 12, 'Guatemala', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (85, 'Special Correspondents (Envoyés très spéciaux)', 11, 'Brazil', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (86, 'Top Secret!', 1, 'Portugal', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (87, 'Skyline', 8, 'Czech Republic', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (88, 'Toronto Stories', 10, 'China', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (89, 'California Dreamin'' (Nesfarsit)', 13, 'China', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (90, 'Rocky III', 7, 'Russia', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (91, 'Bad Teacher', 2, 'Kyrgyzstan', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (92, 'Killer Condom (Kondom des Grauens)', 6, 'Sweden', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (93, 'Gonzo: The Life and Work of Dr. Hunter S. Thompson', 10, 'Peru', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (94, 'Revenge of the Ninja', 11, 'Philippines', 1990);
insert into movie (id, name, director_id, country_of_origin, release_year) values (95, 'Legend of Rita, The (Stille nach dem Schuß, Die)', 16, 'Indonesia', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (96, 'Clara and Me (Clara et moi)', 18, 'China', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (97, 'Prince & Me, The', 17, 'China', 1984);
insert into movie (id, name, director_id, country_of_origin, release_year) values (98, 'Radiohead: Meeting People Is Easy', 14, 'Russia', 1991);
insert into movie (id, name, director_id, country_of_origin, release_year) values (99, 'Funny Bones', 6, 'Cambodia', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (100, 'Vampire Academy', 5, 'Indonesia', 1986);
insert into movie (id, name, director_id, country_of_origin, release_year) values (101, 'The Hyperboloid of Engineer Garin (Giperboloid inzhenera Garina)', 7, 'China', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (102, 'Cruise, The', 3, 'Slovenia', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (103, 'Padrecito, El (Little Priest)', 8, 'Nigeria', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (104, 'Nobody Wants the Night', 13, 'Canada', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (105, 'Sadist, The', 7, 'China', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (106, 'The Bride Wore Red', 9, 'Canada', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (107, 'Leaves from Satan''s Book (Blade af Satans bog)', 1, 'Comoros', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (108, 'Watch Out for the Automobile (Beregis avtomobilya)', 20, 'France', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (109, 'Sleeping Beauty', 10, 'Indonesia', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (110, 'Divide and Conquer (Why We Fight, 3)', 3, 'United States', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (111, 'Book of Stars, The', 9, 'Brazil', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (112, 'Miser, The (L''avare)', 5, 'Australia', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (113, 'Nantucket Film Festival''s Comedy Roundtable', 9, 'Russia', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (114, 'Bad Blood (Mauvais sang)', 10, 'Portugal', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (115, 'American Raspberry (Prime Time) (Funny America)', 7, 'China', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (116, 'Where Were You When the Lights Went Out?', 5, 'Tanzania', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (117, 'She-Wolf of London', 5, 'China', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (118, 'You Only Live Twice', 14, 'Poland', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (119, 'Walk of Shame', 14, 'China', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (120, 'Life and Death of Colonel Blimp, The', 5, 'Portugal', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (121, 'Van Diemen''s Land', 1, 'Sweden', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (122, 'Accidental Spy, The (Dak miu mai shing)', 2, 'China', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (123, 'Undead', 7, 'Poland', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (124, 'Jesus of Montreal (Jésus de Montréal)', 11, 'Russia', 1971);
insert into movie (id, name, director_id, country_of_origin, release_year) values (125, 'Mortal Kombat', 11, 'China', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (126, 'Glen or Glenda', 19, 'Kyrgyzstan', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (127, 'Cincinnati Kid, The', 8, 'France', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (128, 'Afghan Star', 8, 'China', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (129, 'Evangelion: 1.0 You Are (Not) Alone (Evangerion shin gekijôban: Jo)', 12, 'Japan', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (130, 'Sex Is Comedy', 3, 'China', 2003);
insert into movie (id, name, director_id, country_of_origin, release_year) values (131, 'Duo (Pas de deux)', 7, 'Luxembourg', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (132, 'Los Angeles Plays Itself', 6, 'Indonesia', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (133, 'Shark Skin Man and Peach Hip Girl (Samehada otoko to momojiri onna)', 2, 'United States', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (134, 'Passion Flower', 10, 'Sweden', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (135, 'Gantz: Perfect Answer', 16, 'China', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (136, 'Hardware', 5, 'France', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (137, 'Bopha!', 13, 'Dominican Republic', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (138, 'Voyager (Homo Faber)', 19, 'Philippines', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (139, 'Ryan', 10, 'Tanzania', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (140, 'Terminal, The', 20, 'Chile', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (141, 'Silent World, The (Le monde du silence)', 3, 'Peru', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (142, 'Boys from Brazil, The', 1, 'Indonesia', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (143, 'Scary Movie 4', 7, 'China', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (144, 'Hireling, The', 13, 'Philippines', 1989);
insert into movie (id, name, director_id, country_of_origin, release_year) values (145, 'Shaft', 9, 'Greece', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (146, 'Christmas Story, A', 8, 'Poland', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (147, 'So It Goes (Korsoteoria)', 20, 'China', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (148, 'Jar City (Mýrin)', 3, 'Mexico', 1982);
insert into movie (id, name, director_id, country_of_origin, release_year) values (149, 'Malice', 20, 'Colombia', 1985);
insert into movie (id, name, director_id, country_of_origin, release_year) values (150, 'Long Walk Home, The', 12, 'China', 2003);
insert into movie (id, name, director_id, country_of_origin, release_year) values (151, 'Cameron''s Closet', 19, 'Israel', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (152, 'Possessed', 3, 'Indonesia', 1986);
insert into movie (id, name, director_id, country_of_origin, release_year) values (153, 'Outsider', 8, 'United States', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (154, 'The Land Before Time X: The Great Longneck Migration', 20, 'Indonesia', 1985);
insert into movie (id, name, director_id, country_of_origin, release_year) values (155, 'Dog, The', 3, 'Poland', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (156, 'Monkey''s Tale, A (Château des singes, Le)', 11, 'Indonesia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (157, 'Night Falls on Manhattan', 19, 'China', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (158, 'Ikiru', 9, 'Ethiopia', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (159, 'Big Mommas: Like Father, Like Son', 8, 'Indonesia', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (160, 'Trouble Bound', 13, 'Indonesia', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (161, 'Wankers, The (Les branleuses)', 11, 'Portugal', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (162, 'Just 4 Kicks', 19, 'China', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (163, 'Bad Words', 5, 'Peru', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (164, 'Asterix and the Vikings (Astérix et les Vikings)', 9, 'China', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (165, 'Funny Games', 10, 'China', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (166, 'Young Victoria, The', 16, 'Czech Republic', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (167, 'Genealogies of a Crime (Généalogies d''un crime)', 10, 'Zambia', 2003);
insert into movie (id, name, director_id, country_of_origin, release_year) values (168, 'Wall Street', 3, 'Indonesia', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (169, 'Scarlet and the Black, The', 5, 'Argentina', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (170, 'Father and Son (Otets i syn)', 2, 'Portugal', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (171, 'Ramona and Beezus', 16, 'Norway', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (172, 'Adventures of Hajji Baba, The', 6, 'Philippines', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (173, 'We Are Young. We Are Strong.', 10, 'Japan', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (174, 'Le grand soir', 3, 'China', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (175, 'Through and Through (Na wylot)', 7, 'Thailand', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (176, 'King and I, The', 19, 'Tanzania', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (177, 'Streamers', 18, 'Turkmenistan', 1991);
insert into movie (id, name, director_id, country_of_origin, release_year) values (178, 'Funny Man, A (Dirch)', 4, 'Finland', 1987);
insert into movie (id, name, director_id, country_of_origin, release_year) values (179, 'Mystery Team', 3, 'Germany', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (180, 'Mighty Joe Young', 6, 'Indonesia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (181, 'Pekka ja Pätkä salapoliiseina', 12, 'Philippines', 1990);
insert into movie (id, name, director_id, country_of_origin, release_year) values (182, 'Sexual Predator', 20, 'Russia', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (183, 'Hostel: Part II', 9, 'Poland', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (184, 'Israeli Intelligence (Hamosad Hasagur)', 8, 'China', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (185, 'Bullhead (Rundskop)', 2, 'China', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (186, 'Vie meilleure, Une (Better Life, A)', 9, 'France', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (187, 'Affinity', 13, 'Nicaragua', 1961);
insert into movie (id, name, director_id, country_of_origin, release_year) values (188, 'Playing ''In the Company of Men'' (En jouant ''Dans la compagnie des hommes'')', 14, 'Belarus', 1989);
insert into movie (id, name, director_id, country_of_origin, release_year) values (189, 'Gasland Part II', 8, 'Cameroon', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (190, 'Somewhere Between', 9, 'Greece', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (191, 'Cloudland', 18, 'Greece', 1987);
insert into movie (id, name, director_id, country_of_origin, release_year) values (192, 'My Fair Lady', 15, 'Indonesia', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (193, 'The Time of Their Lives', 11, 'Sweden', 1989);
insert into movie (id, name, director_id, country_of_origin, release_year) values (194, 'Police State', 7, 'France', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (195, 'Seduced and Abandoned', 17, 'United Arab Emirates', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (196, 'Scarlet Empress, The', 4, 'Madagascar', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (197, 'Starsky & Hutch', 3, 'China', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (198, 'Fans', 9, 'Guyana', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (199, 'Duplicity', 10, 'China', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (200, 'Crazed Fruit (Kurutta kajitsu)', 15, 'Czech Republic', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (201, 'Tripper, The', 4, 'Nigeria', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (202, 'Apartment 1303 3D', 10, 'Tanzania', 1986);
insert into movie (id, name, director_id, country_of_origin, release_year) values (203, 'Eight Legged Freaks', 12, 'Belarus', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (204, 'Dear God', 17, 'Japan', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (205, 'Pyramid, The', 7, 'China', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (206, 'Best Seller', 17, 'China', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (207, 'Silence, The (Sokout)', 19, 'United States', 2003);
insert into movie (id, name, director_id, country_of_origin, release_year) values (208, 'Jerk Theory, The', 12, 'Mexico', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (209, 'Airport', 16, 'Indonesia', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (210, 'Outsider', 3, 'Indonesia', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (211, 'Dolan''s Cadillac', 14, 'Russia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (212, 'Nocturno 29', 17, 'Indonesia', 1989);
insert into movie (id, name, director_id, country_of_origin, release_year) values (213, 'Blink', 6, 'Indonesia', 1978);
insert into movie (id, name, director_id, country_of_origin, release_year) values (214, 'Jay and Silent Bob Strike Back', 13, 'Russia', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (215, 'In the Fog (V tumane)', 6, 'Greece', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (216, 'Time of Eve (Eve no jikan)', 13, 'Indonesia', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (217, 'Jo Jo Dancer, Your Life is Calling', 6, 'Guinea', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (218, 'Next of Kin', 9, 'Uzbekistan', 1987);
insert into movie (id, name, director_id, country_of_origin, release_year) values (219, 'Casino Royale', 10, 'Belarus', 1967);
insert into movie (id, name, director_id, country_of_origin, release_year) values (220, 'When the Cat''s Away (Chacun cherche son chat)', 19, 'China', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (221, 'White Fang', 18, 'China', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (222, 'To Kill a Priest', 18, 'Croatia', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (223, 'Happy Together', 19, 'Thailand', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (224, 'Trip to Mars, A', 16, 'China', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (225, 'Flight of the Conchords: A Texan Odyssey', 2, 'Serbia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (226, 'Vampire in Venice (Nosferatu a Venezia) (Nosferatu in Venice)', 7, 'Indonesia', 1981);
insert into movie (id, name, director_id, country_of_origin, release_year) values (227, 'Independence Day (a.k.a. ID4)', 13, 'Indonesia', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (228, 'Mulholland Falls', 4, 'China', 1984);
insert into movie (id, name, director_id, country_of_origin, release_year) values (229, 'Iceman, The', 18, 'China', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (230, 'Fairly Odd Movie: Grow Up, Timmy Turner!, A', 14, 'China', 1985);
insert into movie (id, name, director_id, country_of_origin, release_year) values (231, 'Instructions Not Included (No se Aceptan Devoluciones)', 5, 'New Caledonia', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (232, 'Like Water for Chocolate (Como agua para chocolate)', 8, 'Indonesia', 1988);
insert into movie (id, name, director_id, country_of_origin, release_year) values (233, 'Big Red One, The', 18, 'China', 1991);
insert into movie (id, name, director_id, country_of_origin, release_year) values (234, 'Howards of Virginia, The', 3, 'Sweden', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (235, 'Cherry', 4, 'Uzbekistan', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (236, 'Solo', 14, 'China', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (237, 'House Hunting', 19, 'Panama', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (238, 'Hunchback of Notre Dame, The', 8, 'Colombia', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (239, 'Under the Rainbow', 6, 'Poland', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (240, 'Beyond the Valley of the Dolls', 11, 'China', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (241, 'Subject Was Roses, The', 2, 'Greece', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (242, 'About Alex', 19, 'Costa Rica', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (243, 'Bat, The', 10, 'Ecuador', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (244, 'Dedication', 11, 'Kenya', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (245, 'Cube of Sugar, A (Ye Habe Ghand)', 12, 'Brazil', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (246, 'Just Between Friends', 3, 'United States', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (247, '56 Up', 6, 'Poland', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (248, 'Over My Dead Body', 9, 'Argentina', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (249, 'Cantante, El', 20, 'China', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (250, 'Scarface', 12, 'France', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (251, 'Ali: Fear Eats the Soul (Angst essen Seele auf)', 11, 'China', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (252, 'The Remaining', 1, 'Czech Republic', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (253, 'Floating Skyscrapers', 3, 'Indonesia', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (254, 'Muppets Most Wanted', 7, 'France', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (255, 'Celine and Julie Go Boating (Celine et Julie vont en bateau)', 18, 'Indonesia', 1989);
insert into movie (id, name, director_id, country_of_origin, release_year) values (256, 'Grumpy Cat''s Worst Christmas Ever', 17, 'United States', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (257, 'Silentium', 10, 'China', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (258, 'Birds of America', 11, 'Burkina Faso', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (259, 'Mouse Hunt', 16, 'China', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (260, 'Village of the Damned', 18, 'Croatia', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (261, 'Dude, Where''s My Car?', 12, 'China', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (262, 'Fantastic Four, The', 4, 'Saudi Arabia', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (263, 'Voices from the List', 3, 'Indonesia', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (264, 'Weddings and Babies ', 18, 'Macedonia', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (265, 'Narco Cultura', 5, 'Latvia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (266, 'Grace Is Gone', 7, 'Albania', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (267, 'Crossworlds', 17, 'Afghanistan', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (268, 'Freeheld', 6, 'Indonesia', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (269, 'D3: The Mighty Ducks', 17, 'China', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (270, 'Give ''em Hell, Malone', 13, 'Czech Republic', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (271, 'Richard III', 14, 'China', 1989);
insert into movie (id, name, director_id, country_of_origin, release_year) values (272, 'O-Bi, O-Ba - The End of Civilization (O-bi, O-ba - Koniec cywilizacji)', 16, 'Bolivia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (273, 'Kid Galahad', 7, 'United States', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (274, 'High Fidelity', 12, 'Tanzania', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (275, 'Mesmerist, The', 15, 'Croatia', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (276, 'Nitro Circus: The Movie', 13, 'Portugal', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (277, 'Snapshot', 12, 'Ukraine', 1960);
insert into movie (id, name, director_id, country_of_origin, release_year) values (278, 'Keeper of Lost Causes, The (Kvinden i buret)', 9, 'Armenia', 1985);
insert into movie (id, name, director_id, country_of_origin, release_year) values (279, 'I Am Comic', 6, 'Ivory Coast', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (280, 'She Cried No (Freshman Fall)', 20, 'Indonesia', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (281, 'Benji: Off the Leash!', 1, 'Ireland', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (282, 'The Nautical Chart', 7, 'Russia', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (283, 'Maria Full of Grace (Maria, Llena eres de gracia)', 20, 'Russia', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (284, 'Russell Peters: The Green Card Tour - Live from the O2 Arena', 20, 'Philippines', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (285, 'Iron Sky', 7, 'China', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (286, 'Rare Breed, The', 6, 'Denmark', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (287, 'Kid With a Bike, The (Le gamin au vélo)', 8, 'Chad', 1985);
insert into movie (id, name, director_id, country_of_origin, release_year) values (288, 'Age of Innocence, The', 14, 'Madagascar', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (289, 'Faithless', 7, 'Indonesia', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (290, 'Ruby Gentry', 8, 'Brazil', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (291, 'Woods, The', 11, 'Indonesia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (292, 'Septien', 5, 'Indonesia', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (293, 'Gaslight', 6, 'Guinea', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (294, 'Get Out Your Handkerchiefs (Préparez vos mouchoirs)', 16, 'China', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (295, 'Passage to India, A', 11, 'Philippines', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (296, 'Pee-wee''s Big Adventure', 11, 'China', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (297, 'Story of Women (Affaire de femmes, Une)', 14, 'Philippines', 1961);
insert into movie (id, name, director_id, country_of_origin, release_year) values (298, 'Invasion of the Bee Girls', 17, 'North Korea', 1978);
insert into movie (id, name, director_id, country_of_origin, release_year) values (299, 'Deadly Voyage', 11, 'Portugal', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (300, 'Once Upon a Time in America', 18, 'Nicaragua', 1988);
insert into movie (id, name, director_id, country_of_origin, release_year) values (301, 'Tough and Deadly', 10, 'Indonesia', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (302, 'Dragon Eyes', 19, 'Croatia', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (303, 'Welcome to Collinwood', 1, 'Bhutan', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (304, 'Earth (Tierra)', 9, 'Poland', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (305, 'Arrowhead', 7, 'France', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (306, 'Last Legion, The', 11, 'Japan', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (307, 'Carriers Are Waiting, The (Convoyeurs attendent, Les)', 17, 'China', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (308, 'Karlsson Brothers (Bröderna Karlsson)', 14, 'Poland', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (309, 'American Roulette', 19, 'Brazil', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (310, 'Driven', 7, 'Portugal', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (311, 'Bob the Butler', 14, 'Thailand', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (312, 'Haunted House', 15, 'China', 1984);
insert into movie (id, name, director_id, country_of_origin, release_year) values (313, 'Mediterraneo', 13, 'United States', 1988);
insert into movie (id, name, director_id, country_of_origin, release_year) values (314, 'Catch a Fire', 17, 'Australia', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (315, 'Heartbeats (Les amours imaginaires)', 16, 'Peru', 1988);
insert into movie (id, name, director_id, country_of_origin, release_year) values (316, 'From the Hip', 1, 'United States', 1991);
insert into movie (id, name, director_id, country_of_origin, release_year) values (317, 'Forgotten Silver', 5, 'Portugal', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (318, 'Amityville 1992: It''s About Time', 1, 'Canada', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (319, 'Rapado', 9, 'Cuba', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (320, 'Fan, The', 1, 'Philippines', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (321, 'One to Another (Chacun sa nuit)', 15, 'Indonesia', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (322, 'Wanderers, The', 16, 'Canada', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (323, 'For My Father (Sof Shavua B''Tel Aviv)', 8, 'Portugal', 1953);
insert into movie (id, name, director_id, country_of_origin, release_year) values (324, 'Under the Bridges (Unter den Brücken)', 17, 'China', 2003);
insert into movie (id, name, director_id, country_of_origin, release_year) values (325, 'Scavenger Hunt', 7, 'Russia', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (326, 'Tokyo Decadence (Topâzu)', 3, 'China', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (327, 'Dragonworld', 14, 'Indonesia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (328, 'She Does Not Drink, Smoke or Flirt But... She Talks', 14, 'Colombia', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (329, 'The Forgotten Space', 4, 'Finland', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (330, 'Liv & Ingmar', 13, 'China', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (331, 'My Gun is Quick', 18, 'Russia', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (332, 'Ganes', 7, 'Honduras', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (333, 'Andy Hardy''s Double Life', 12, 'Guatemala', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (334, 'Tell Me Something (Telmisseomding)', 1, 'Brazil', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (335, 'Take Her, She''s Mine', 5, 'Japan', 2003);
insert into movie (id, name, director_id, country_of_origin, release_year) values (336, 'Four Daughters', 20, 'China', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (337, 'Fright Night', 15, 'France', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (338, 'Moon Warriors, The (Zhan shen chuan shuo)', 13, 'Russia', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (339, 'Vagabond (Sans toit ni loi)', 12, 'Sweden', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (340, 'Ricochet', 7, 'Canada', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (341, 'Play', 13, 'Sweden', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (342, 'Goodbye World', 10, 'Philippines', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (343, 'Primus Hallucino-Genetics Live 2004', 16, 'Indonesia', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (344, 'Spy Kids', 16, 'Albania', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (345, 'The Adventures of André and Wally B.', 11, 'Pakistan', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (346, 'Scent of Green Papaya, The (Mùi du du xhan - L''odeur de la papaye verte)', 8, 'Indonesia', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (347, 'My Sister''s Keeper', 9, 'Philippines', 1969);
insert into movie (id, name, director_id, country_of_origin, release_year) values (348, 'My Sex Life... or How I Got Into an Argument (Comment je me suis disputé... (ma vie sexuelle))', 12, 'Japan', 2013);
insert into movie (id, name, director_id, country_of_origin, release_year) values (349, 'Prince of Jutland (a.k.a. Royal Deceit)', 13, 'China', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (350, 'Handle with Care (a.k.a. Citizen''s Band)', 7, 'China', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (351, '7th Voyage of Sinbad, The', 17, 'Philippines', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (352, 'Portrait in Black', 20, 'Portugal', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (353, 'A Smoky Mountain Christmas', 2, 'Indonesia', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (354, 'Recruit, The', 10, 'Colombia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (355, 'Last of the Mohicans, The', 14, 'Poland', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (356, 'Happy Event, A (Un Heureux Evénement)', 2, 'China', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (357, 'Prata Palomares', 13, 'China', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (358, 'Casino Royale', 16, 'Japan', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (359, 'History of the World: Part I', 14, 'Malaysia', 1990);
insert into movie (id, name, director_id, country_of_origin, release_year) values (360, 'A Cry in the Wild', 11, 'Ukraine', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (361, 'Park Avenue: Money, Power and the American Dream', 6, 'Albania', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (362, 'Soldier''s Sweetheart, A', 1, 'China', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (363, 'Time of the Gypsies (Dom za vesanje)', 6, 'Indonesia', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (364, 'Coluche, l''histoire d''un mec', 18, 'Ukraine', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (365, 'Moby Dick', 13, 'Brazil', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (366, 'Texas Carnival', 4, 'Estonia', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (367, 'Ghosts of Girlfriends Past', 10, 'Central African Republic', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (368, 'New World (Shin-sae-gye)', 14, 'Philippines', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (369, 'Toy Story Toons: Partysaurus Rex', 8, 'Russia', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (370, 'Cold Moon (Lune froide)', 11, 'Mauritius', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (371, 'Rockers', 5, 'Vietnam', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (372, 'Swarm, The', 10, 'China', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (373, 'The Wrecking Crew', 15, 'Poland', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (374, 'Fat City', 4, 'China', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (375, 'Under Siege 2: Dark Territory', 14, 'Paraguay', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (376, 'Golem, The (Golem, wie er in die Welt kam, Der)', 5, 'Sweden', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (377, 'Nicky''s Family', 16, 'China', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (378, 'Jönssonligans största kupp', 8, 'Portugal', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (379, 'Moonlight and Valentino', 1, 'Philippines', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (380, 'Stray Dog (Nora inu)', 17, 'Nigeria', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (381, 'Strategy of the Snail, The (Estrategia del Caracol, La)', 17, 'Venezuela', 1990);
insert into movie (id, name, director_id, country_of_origin, release_year) values (382, 'Personal Velocity', 10, 'Czech Republic', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (383, 'Death Note', 10, 'Canada', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (384, 'Late Quartet, A', 12, 'Ukraine', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (385, 'The Black Devil', 15, 'Russia', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (386, 'Resident Evil: Damnation', 13, 'United States', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (387, 'Bunker, The', 4, 'Nigeria', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (388, 'Lincz', 17, 'Russia', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (389, 'Dragonheart 2: A New Beginning', 20, 'Ecuador', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (390, 'Study in Choreography for Camera, A', 20, 'Czech Republic', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (391, 'Red: Werewolf Hunter', 4, 'Indonesia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (392, 'Peacemaker, The', 16, 'Poland', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (393, 'Detonator, The', 4, 'Philippines', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (394, 'Bob Roberts', 13, 'China', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (395, 'The Invitation', 13, 'China', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (396, 'Jungle Creature: Hugo, The (Jungledyret) (Go Hugo Go)', 11, 'Bosnia and Herzegovina', 1988);
insert into movie (id, name, director_id, country_of_origin, release_year) values (397, 'Howards End', 7, 'Sweden', 2003);
insert into movie (id, name, director_id, country_of_origin, release_year) values (398, 'Cutlet for Three (Ein Schnitzel für drei)', 2, 'Sweden', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (399, 'Smokey and the Bandit II', 2, 'Japan', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (400, '100 Men and a Girl (One Hundred Men and a Girl)', 14, 'Pakistan', 1987);
insert into movie (id, name, director_id, country_of_origin, release_year) values (401, 'To Begin Again (a.k.a. Starting Over) (Volver a Empezar)', 18, 'China', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (402, 'Kiss, The', 19, 'Albania', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (403, 'Most Hated Family in America, The', 19, 'China', 1985);
insert into movie (id, name, director_id, country_of_origin, release_year) values (404, 'Lullaby', 6, 'France', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (405, 'Limit (Limite)', 20, 'Indonesia', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (406, 'Kevin Smith: Sold Out - A Threevening with Kevin Smith', 9, 'Morocco', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (407, 'Lady Chatterley''s Lover', 12, 'Iran', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (408, 'Madhouse', 12, 'Philippines', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (409, 'Better Luck Tomorrow', 20, 'France', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (410, 'Sun Also Rises, The (Tai yang zhao chang sheng qi)', 14, 'Indonesia', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (411, 'Unmade Beds', 19, 'China', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (412, 'Indian Summer (a.k.a. Alive & Kicking)', 19, 'Canada', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (413, 'Smart Money', 14, 'Poland', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (414, 'Lathe of Heaven, The', 20, 'Philippines', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (415, 'In Football We Trust', 11, 'China', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (416, 'Mirror Has Two Faces, The', 9, 'Saudi Arabia', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (417, 'Uncle Sam', 7, 'Colombia', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (418, 'Haunted House, A', 13, 'China', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (419, 'Leif', 1, 'China', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (420, '10 Things I Hate About You', 2, 'Estonia', 1984);
insert into movie (id, name, director_id, country_of_origin, release_year) values (421, 'Flight 93', 17, 'Colombia', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (422, 'Death in Venice (Morte a Venezia)', 14, 'Russia', 1986);
insert into movie (id, name, director_id, country_of_origin, release_year) values (423, 'Rough Riders', 12, 'Sweden', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (424, '99 Homes', 3, 'France', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (425, 'All the Mornings of the World (Tous les matins du monde)', 17, 'China', 2007);
insert into movie (id, name, director_id, country_of_origin, release_year) values (426, 'Man Who Left His Will on Film, The (Tôkyô sensô sengo hiwa)', 18, 'China', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (427, 'Slappy and the Stinkers', 15, 'Japan', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (428, 'Hercules in New York', 13, 'Peru', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (429, 'The Periwig-Maker', 2, 'Indonesia', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (430, 'China O''Brien', 4, 'Colombia', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (431, 'Boxing Gym', 18, 'Thailand', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (432, 'Play It Again, Sam', 17, 'Cameroon', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (433, 'Old Boy', 8, 'Mexico', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (434, 'Ornamental Hairpin (Kanzashi)', 17, 'Russia', 1989);
insert into movie (id, name, director_id, country_of_origin, release_year) values (435, 'Beautiful Creatures', 19, 'Sweden', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (436, 'Liebelei', 12, 'Pakistan', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (437, 'Month in the Country, A', 10, 'Philippines', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (438, 'Blood and Black Lace (Sei donne per l''assassino)', 6, 'Russia', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (439, 'Out of Balance: ExxonMobil''s Impact on Climate Change', 9, 'Canada', 1996);
insert into movie (id, name, director_id, country_of_origin, release_year) values (440, 'Body of War', 17, 'Indonesia', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (441, 'Zatoichi and the Chess Expert (Zatôichi Jigoku tabi) (Zatôichi 12)', 1, 'Guatemala', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (442, 'Ouch (Aïe)', 1, 'Mongolia', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (443, 'Nicht alle waren Mörder', 19, 'China', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (444, 'Mother Wore Tights', 11, 'Indonesia', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (445, 'Avengers, The', 1, 'Chile', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (446, 'Lonely Hearts', 3, 'China', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (447, 'Red Chapel (Røde kapel)', 18, 'France', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (448, 'In Search of a Midnight Kiss', 3, 'Brazil', 2003);
insert into movie (id, name, director_id, country_of_origin, release_year) values (449, 'When Worlds Collide', 8, 'Syria', 1999);
insert into movie (id, name, director_id, country_of_origin, release_year) values (450, 'Big Country, The', 15, 'Pakistan', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (451, 'Cassandra''s Dream', 10, 'China', 1984);
insert into movie (id, name, director_id, country_of_origin, release_year) values (452, 'Spiral', 15, 'China', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (453, 'Goodbye Again', 2, 'Philippines', 1992);
insert into movie (id, name, director_id, country_of_origin, release_year) values (454, 'Seventh Horse of the Sun  (Suraj Ka Satvan Ghoda)', 12, 'Thailand', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (455, 'Pulp Fiction', 14, 'Indonesia', 2003);
insert into movie (id, name, director_id, country_of_origin, release_year) values (456, 'Shanghai', 12, 'Japan', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (457, 'Sweethearts', 13, 'China', 2002);
insert into movie (id, name, director_id, country_of_origin, release_year) values (458, 'Albino Alligator', 6, 'Indonesia', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (459, 'The Facility', 1, 'China', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (460, 'Legend of the Black Scorpion (a.k.a. The Banquet) (Ye yan)', 5, 'Guatemala', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (461, 'Escape Me Never', 9, 'Lithuania', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (462, 'Atragon (Kaitei Gunkan)', 5, 'China', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (463, 'Aziz Ansari: Intimate Moments for a Sensual Evening', 18, 'Colombia', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (464, 'Let''s Go to Prison', 6, 'China', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (465, 'Pitfall', 7, 'French Polynesia', 2004);
insert into movie (id, name, director_id, country_of_origin, release_year) values (466, 'Prize, The', 4, 'China', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (467, 'Bridge Too Far, A', 9, 'United States', 2005);
insert into movie (id, name, director_id, country_of_origin, release_year) values (468, 'Man on the Roof, The (Mannen på taket)', 16, 'Philippines', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (469, 'Empty Mirror, The', 16, 'Sri Lanka', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (470, 'Things Change', 14, 'Indonesia', 2010);
insert into movie (id, name, director_id, country_of_origin, release_year) values (471, 'Irresistible', 12, 'China', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (472, 'Why Are the Bells Ringing, Mitica? (a.k.a. Carnival Scenes) (De ce trag clopotele, Mitica?)', 18, 'Philippines', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (473, 'Friend of the Deceased, A (Priyatel pokonika)', 17, 'Uzbekistan', 2000);
insert into movie (id, name, director_id, country_of_origin, release_year) values (474, 'Defenseless', 10, 'El Salvador', 2012);
insert into movie (id, name, director_id, country_of_origin, release_year) values (475, 'Bingo Long Traveling All-Stars & Motor Kings, The', 15, 'Sri Lanka', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (476, 'Belle comme la femme d''un autre', 7, 'Syria', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (477, 'Muhammad Ali''s Greatest Fight', 19, 'Indonesia', 1990);
insert into movie (id, name, director_id, country_of_origin, release_year) values (478, 'Bitter Sweet', 7, 'China', 2001);
insert into movie (id, name, director_id, country_of_origin, release_year) values (479, 'Ballplayer: Pelotero', 4, 'Portugal', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (480, 'Happy Accidents', 10, 'Thailand', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (481, 'Beauty Prize', 3, 'Russia', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (482, 'Girl, Interrupted', 12, 'Greece', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (483, 'Blondie of the Follies', 1, 'Sweden', 1998);
insert into movie (id, name, director_id, country_of_origin, release_year) values (484, 'Rent-a-Cat', 18, 'Philippines', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (485, 'Under Suspicion', 16, 'Canada', 1990);
insert into movie (id, name, director_id, country_of_origin, release_year) values (486, 'Funny Bones', 4, 'Ukraine', 1995);
insert into movie (id, name, director_id, country_of_origin, release_year) values (487, 'The Loft', 2, 'Argentina', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (488, 'Attila', 7, 'Brazil', 2009);
insert into movie (id, name, director_id, country_of_origin, release_year) values (489, 'Olsen Gang, The (Olsen-Banden)', 17, 'Thailand', 1997);
insert into movie (id, name, director_id, country_of_origin, release_year) values (490, 'Cats', 10, 'Philippines', 2006);
insert into movie (id, name, director_id, country_of_origin, release_year) values (491, 'Without Lying Down: Frances Marion and the Power of Women in Hollywood', 17, 'China', 1984);
insert into movie (id, name, director_id, country_of_origin, release_year) values (492, 'Dieta mediterránea', 12, 'Yemen', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (493, 'Good Advice', 9, 'Marshall Islands', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (494, 'Grifters, The', 10, 'Kazakhstan', 2011);
insert into movie (id, name, director_id, country_of_origin, release_year) values (495, 'X-Files: I Want to Believe, The', 8, 'Russia', 1986);
insert into movie (id, name, director_id, country_of_origin, release_year) values (496, 'Knockaround Guys', 7, 'Brazil', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (497, 'Hide in Plain Sight', 13, 'Czech Republic', 1993);
insert into movie (id, name, director_id, country_of_origin, release_year) values (498, 'Death Sentence', 7, 'Russia', 2008);
insert into movie (id, name, director_id, country_of_origin, release_year) values (499, 'Bit by Bit', 16, 'Philippines', 1994);
insert into movie (id, name, director_id, country_of_origin, release_year) values (500, 'Fur: An Imaginary Portrait of Diane Arbus', 10, 'Indonesia', 2001);
